// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebAPI.Data;

namespace TestWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("TestWebAPI.models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEP = "18300-530",
                            CPF = "106.723.510-80",
                            Cidade = "Capão Bonito",
                            Email = "Jonas@gmail.com",
                            Estado = "São Paulo",
                            Logradouro = "Avenida Santos Dumont.",
                            Nacionalidade = "Brasileiro",
                            Nome = "Jonas",
                            Sobrenome = "Montero",
                            Telefone = "3175-6848"
                        },
                        new
                        {
                            Id = 2,
                            CEP = "88355-660",
                            CPF = "198.454.220-63",
                            Cidade = "Brusque",
                            Email = "Kaique@protonmail.com",
                            Estado = "Santa Catarina",
                            Logradouro = "Rua Domingos Altair de Melo",
                            Nacionalidade = "Português",
                            Nome = "Kaique",
                            Sobrenome = "Fagundes",
                            Telefone = "3137-4428"
                        },
                        new
                        {
                            Id = 3,
                            CEP = "68926-162",
                            CPF = "922.696.940-07",
                            Cidade = "Santana",
                            Email = "Sylas@protonmail.com",
                            Estado = "Amapá",
                            Logradouro = "Rua D 14",
                            Nacionalidade = "Inglês",
                            Nome = "Sylas",
                            Sobrenome = "Lancaster",
                            Telefone = "2776-5574"
                        },
                        new
                        {
                            Id = 4,
                            CEP = "69303-037",
                            CPF = "268.320.060-98",
                            Cidade = "Boa Vista",
                            Email = "Isaya@hotmail.com",
                            Estado = "Roraima",
                            Logradouro = "Rua Amajari",
                            Nacionalidade = "Inglês",
                            Nome = "Isaya",
                            Sobrenome = "Otomano",
                            Telefone = "3836-3348"
                        },
                        new
                        {
                            Id = 5,
                            CEP = "35302-405",
                            CPF = "161.443.780-73",
                            Cidade = "Caratinga",
                            Email = "Marlon@hotmail.com",
                            Estado = "Minas Gerais",
                            Logradouro = "Rua Rubens Gomes",
                            Nacionalidade = "Brasileiro",
                            Nome = "Marlon",
                            Sobrenome = "Silva",
                            Telefone = "3071-0045"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
